service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - ${file(config/iam/SendMailIAM.yml):SendMailIAM}
  environment:
    REGION: eu-west-1
    SENDER_MAIL: ranjan.manish421@gmail.com

resources:
  Resources:
    MailQueue: ${file(config/resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(config/resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(config/resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
